name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history to get the full commit message

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install semantic-release and plugins
        run: npm install --no-save semantic-release @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
