stages:
  - test

unit-test-job:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_TITLE !~ /^(Draft|WIP):/i
      when: always
    - when: never
  script:
    - echo "Running unit tests"
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_tests.sh