stages:
  - test
  - post-merge
  - release

unit-test-job:
  coverage: '/TOTAL.*\s+(\d+%)$/'
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_TITLE !~ /^(Draft|WIP):/i  # Run on branches that request to merge into main
      when: always
    - when: never
  script:
    - echo "Running unit tests"
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_tests.sh

post-merge-job:
  coverage: '/TOTAL.*\s+(\d+%)$/'
  stage: post-merge
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run on main branch after merge
      when: always
    - when: never
  script:
    - echo "Running post-merge tests"
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_tests.sh

create_release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is pushed
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
    # TODO: Create updated version of `cifutils_latest.sif` apptainer on digs
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release notes for version $CI_COMMIT_TAG'
