"""
atomworks.ml - Machine Learning utilities for biological data.

This subpackage provides datasets, preprocessing, pipelines, and other ML utilities
for biological data, originally from the atomworks.ml package.
"""
import logging
import os
import warnings

warnings.filterwarnings("once", message="All-NaN slice encountered", category=RuntimeWarning)

logger = logging.getLogger("atomworks.ml")
_log_level = os.environ.get("ATOMWORKS_ML_LOG_LEVEL", os.environ.get("ATOMWORKS_LOG_LEVEL", "WARNING")).upper()
logger.setLevel(_log_level)


def _get_versioning(repo_path: str) -> str:
    """
    Get the version string of the current git repository.

    The returned version string will be of the form:
        - <tag>[+dev{<commit_count>}.<commit_hash>][-dirty]

    [+dev{<commit_count>}.<commit_hash>] is only present if there are commits since
        the latest tag. The commit count is the number of commits between the latest
        tag and the current HEAD commit. The commit hash is the first 7 characters
        of the commit hash.
    [-dirty] is only present if there are uncommitted changes.
    """
    os.environ["GIT_PYTHON_REFRESH"] = "silent"
    import git

    repo = git.Repo(repo_path, search_parent_directories=True)

    # (1) Get latest tag
    latest_tag = sorted(repo.tags, key=lambda t: t.commit.committed_datetime)[-1]
    version = str(latest_tag)

    # (2) Check for commits since latest tag
    if latest_tag.commit != repo.head.commit:
        # Count commits between latest tag and HEAD
        commit_count = len(list(repo.iter_commits(f"{latest_tag.commit}..HEAD")))
        version += f"+dev{commit_count}.{repo.head.commit.hexsha[:7]}"

    # (3) Check for uncommitted changes
    if repo.is_dirty(untracked_files=True):
        version += "-dirty"

    return version


## monkey patch biotite to allow override of hbond distance in 'base_pairs'
import biotite.structure as struc  # noqa: E402

from atomworks.ml.transforms.dna.pad_dna import base_pairs  # noqa: E402

struc.base_pairs = base_pairs


__version__ = None
__version_tuple__ = None
try:
    __version__ = __version__ or _get_versioning(os.path.dirname(os.path.realpath(__file__)))
    assert __version__ is not None
except Exception as e:
    try:
        # NOTE: If repo is installed as package via pip (e.g. in a production environment),
        #       the version.py file is automatically generated by hatch-vcs.
        from atomworks.ml.version import __version__, __version_tuple__
    except ImportError:
        __version__ = "?"
        __version_tuple__ = (0, 0, 0)
        logger.warning(f"Failed to get versioning. Setting version to '?'. Error: {e}")
