"""Enums for atomworks.ml"""

from enum import IntEnum, StrEnum, auto


class GroundTruthConformerPolicy(IntEnum):
    """Enum for ground truth conformer policy.

    Possible values are:
        -  REPLACE: Use the ground-truth coordinates as the reference conformer, replacing the coordinated generated by RDKit in-place (and add a flag to indicate that the coordinates were replaced)
        -  ADD: Return an additional feature (with the same shape as `ref_pos`) containing the ground-truth coordinates
        -  FALLBACK: Use the ground-truth coordinates only if our standard conformer generation pipeline fails (e.g., we cannot generate a conformer with RDKit,
            and the molecule is either not in the CCD or the CCD entry is invalid)
        -  IGNORE: Do not use the ground-truth coordinates as the reference conformer under any circumstances
    """

    REPLACE = 1
    ADD = 2
    FALLBACK = 3
    IGNORE = 4


class HydrogenPolicy(StrEnum):
    """Enum for hydrogen policy.

    Possible values are:
        -  KEEP: Keep the hydrogens as they are
        -  REMOVE: Remove the hydrogens
        -  INFER: Infer the hydrogens from the atom array
    """

    KEEP = auto()
    REMOVE = auto()
    INFER = auto()
