import logging
import os

import numpy as np

from cifutils.parser import parse

# Set global logging level to `WARNING` if not set by user
logger = logging.getLogger("cifutils")
_log_level = os.environ.get("CIFUTILS_LOG_LEVEL", "WARNING").upper()
logger.setLevel(_log_level)


def _get_versioning(repo_path: str) -> str:
    """
    Get the version string of the current git repository.

    The returned version string will be of the form:
        - <tag>[+dev{<commit_count>}.<commit_hash>][-dirty]

    [+dev{<commit_count>}.<commit_hash>] is only present if there are commits since
        the latest tag. The commit count is the number of commits between the latest
        tag and the current HEAD commit. The commit hash is the first 7 characters
        of the commit hash.
    [-dirty] is only present if there are uncommitted changes.
    """
    os.environ["GIT_PYTHON_REFRESH"] = "silent"
    import git

    repo = git.Repo(repo_path, search_parent_directories=True)

    # (1) Get latest tag
    latest_tag = sorted(repo.tags, key=lambda t: t.commit.committed_datetime)[-1]
    version = str(latest_tag)

    # (2) Check for commits since latest tag
    if latest_tag.commit != repo.head.commit:
        # Count commits between latest tag and HEAD
        commit_count = len(list(repo.iter_commits(f"{latest_tag.commit}..HEAD")))
        version += f"+dev{commit_count}.{repo.head.commit.hexsha[:7]}"

    # (3) Check for uncommitted changes
    if repo.is_dirty(untracked_files=True):
        version += "-dirty"

    return version


__version__ = None
__version_tuple__ = None
try:
    __version__ = _get_versioning(os.path.dirname(os.path.abspath(__file__)))
    assert __version__ is not None
except Exception as e:
    try:
        # NOTE: If cifutils is installed as package via pip (e.g. in a production environment),
        #       the version.py file is automatically generated by hatch-vcs.
        from cifutils.version import __version__, __version_tuple__
    except ImportError:
        __version__ = "?"
        __version_tuple__ = (0, 0, 0)
        logger.warning(f"Failed to get versioning. Setting version to '?'. Error: {e}")

# Monkey patch biotite
import biotite.structure as struc  # noqa: E402

from cifutils.utils.selection import get_residue_starts  # noqa: E402

struc.get_residue_starts = get_residue_starts


# TODO: Remove this patch with biotite 1.0.2 if #714 gets merged
def equal_annotations(self, item, equal_nan: bool = True) -> bool:  # noqa: ANN001
    """
    Check, if this object shares equal annotation arrays with the
    given :class:`AtomArray` or :class:`AtomArrayStack`.

    Parameters
    ----------
    item : AtomArray or AtomArrayStack
        The object to compare the annotation arrays with.
    equal_nan: bool
        Whether to count `nan` values as equal. Default: True.

    Returns:
    -------
    equality : bool
        True, if the annotation arrays are equal.
    """
    if not isinstance(item, struc.atoms._AtomArrayBase):
        return False
    if not self.equal_annotation_categories(item):
        return False
    for name in self._annot:
        # ... allowing `nan` values causes type-casting, which is only possible for floating-point arrays
        allow_nan = equal_nan if np.issubdtype(self._annot[name].dtype, np.floating) else False
        if not np.array_equal(
            self._annot[name],
            item._annot[name],
            equal_nan=allow_nan,
        ):
            return False
    return True


struc.atoms._AtomArrayBase.equal_annotations = equal_annotations
