"""
Python script to generate multiple sequence alignments (MSAs) for structure prediction models.
Based on the original bash script written by Ivan Anishchenko: https://github.com/baker-laboratory/rosettafold-all-atom/blob/6c8514053acf76da0f9edde2aa51b40abff68fa1/make_msa.sh#l4

Example usage:
    python make_msa.py --sequence-str "MEGDDLFDEFGNLIGVDPF..." --out-dir "/path/to/output/directory" --cpu 4 --mem 8
"""

import argparse
import logging
import os
import random
import shutil
import subprocess
import time
from datetime import datetime
from os import PathLike
from pathlib import Path

import pandas as pd

from atomworks.ml.preprocessing.constants import NA_VALUES
from atomworks.ml.utils.misc import hash_sequence

bfd_db_path = "/local/databases/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt"
uniref30_db_path = "/local/databases/uniclust/UniRef30_2022_02"
# template_db_path = "/projects/ml/TrRosetta/pdb100_2022Apr19/pdb100_2022Apr19" # NOTE: Not currently used, as we're not running HHsearch with the template database

# Prepend the HHlib path to the path environment variable
os.environ["PATH"] = "/software/hhsuite/build/bin/:" + os.environ["PATH"]

# Setup logfile
script_dir = Path(__file__).resolve().parent
logs_dir = script_dir / "logs" / datetime.now().strftime("%Y%m%d_%H%M%S")
logs_dir.mkdir(parents=True, exist_ok=True)
log_file = logs_dir / "script.log"

# Configure logging to output to the log file
print(f"Logging to file: {log_file}")
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(log_file),
        logging.StreamHandler(),  # Also output to console
    ],
)

logger = logging.getLogger(__name__)


def run_hhblits(
    input_file: PathLike, output_file: PathLike, db_path: PathLike, cpu: int, mem: int, e_value: float, all_flag: bool
) -> None:
    """
    Run HHblits against a specified database to generate a multiple sequence alignment.
    HHblits is the faster, more memory-efficient version of HHsearch.

    Args:
        input_file (str): Path to the input fasta file. may contain a single sequence or a partial msa (e.g., from a previous iteration).
        output_file (str): Path to the desired output a3m file. we will write the resultant msa with significant matches in a3m format to this file.
        db_path (str): HHsuite database path. For the digs, should point to `local` to avoid unecessary I/O.
        cpu (int): Number of cpus to use. hhblits default is 2. rf2aa default is 4.
        mem (int): Maximum memory to use, in GB. hhblits default is 3. rf2aa default is 64.
        e_value (float): E-value threshold for inclusion in result alignemnt. hhblits default is 0.001.
        all_flag (bool): Whether to keep all sequences in the msa (useful when pairing).

    Reference:
        - HHblits documentation: https://github.com/soedinglab/hh-suite/wiki#hhblits--hmm-hmm-based-lighting-fast-iterative-sequence-search
    """
    # For details on the hhblits command, see: https://github.com/soedinglab/hh-suite/wiki
    hhblits_cmd = f"hhblits -i {input_file} -oa3m {output_file} -o /dev/null -mact 0.35 -maxfilt 10000000 -neffmax 20 -cov 25 -cpu {cpu} -nodiff -realign_max 100000000 -maxseq 1000000 -maxmem {mem} -n 4 -d {db_path} -e {e_value} -v 0"

    # The -all flag turns off the filtering of the resultant msa; we may want to consider using when pairing MSAs is important
    if all_flag:
        hhblits_cmd += " -all"
    logger.debug(f"Running HHblits with command: {hhblits_cmd}")
    subprocess.run(hhblits_cmd, shell=True, check=True)


def run_hhfilter(input_file: PathLike, output_file: PathLike, maxseq: int, id: float, cov: float) -> None:
    """
    Run HHfilter on the specified input file.
    HHfilter is used to filter the msa generated by hhblits by maximum sequence identity, coverage, and other criteria.

    Args:
        input_file (str): Path to the input a3m file (created by hhblits, above).
        output_file (str): Where to save the filtered msa output file.
        maxseq (int): Maximum number of sequences to keep in the output msa.
        id (int): Maximum pairwise sequence identity (%). hhfilter default is 90.
        cov (int): Minimum coverage with query (%). hhfilter default is 0. a reasonable value is 50, if following hhblits with -all flag.

    Reference:
        - HHfilter documentation: https://github.com/soedinglab/hh-suite/wiki#hhfilter--filter-an-msa
    """
    hhfilter_cmd = f"hhfilter -maxseq {maxseq} -id {id} -cov {cov} -i {input_file} -o {output_file}"
    logger.debug(f"running hhfilter with command: {hhfilter_cmd}")
    subprocess.run(hhfilter_cmd, shell=True, check=True)


def process_multiple_fasta_strings(sequence_strings: list, out_dir: str, cpu: int = 4, mem: int = 64) -> None:
    """
    Process multiple FASTA sequences to generate multiple sequence alignments (MSAs).

    This function creates a directory structure within the specified `out_dir` and processes each sequence string
    to generate MSAs using iterative searches against sequence databases. The directory structure is organized as follows:

    Ultimately, users shoould remove the `tmp` directory after processing is complete, as it is only used for temporary storage.

    - out_dir/
        - tmp/
            - seq_hash_1/
                - t000_seq_hash1.1e-3.bfd.a3m
                - ...
            - seq_hash_2/
                - ...
        - processed/
            - seq_hash1/
                - seq_hash1.fasta
                - seq_hash1.msa0.a3m
                - seq_hash1.ss2
                - seq_hash1.hhr
            - seq_hash2/
                - ...
            - ...

    Args:
        sequence_strings (list): A list of sequence strings to be processed.
        out_dir (str): The output directory where the results will be saved.
        cpu (int, optional): The number of CPUs to use for processing. Default is 4.
        mem (int, optional): The maximum memory to use, in GB. Default is 64.
    """
    # ...create output directory if it doesn't exist
    Path(out_dir).mkdir(parents=True, exist_ok=True)

    for sequence_string in sequence_strings:
        # ...generate a hash for the sequence that we're processing
        seq_hash = hash_sequence(sequence_string)

        # ...create a unique directory for the output and temporary for this sequence
        final_seq_dir = Path(out_dir) / "processed" / f"{seq_hash}"
        tmp_seq_dir = Path(out_dir) / "tmp" / f"{seq_hash}"

        if not Path(final_seq_dir).exists():
            # ...process the sequence string
            logger.info(
                f"+------------------------ Processing sequence with hash: {seq_hash} and first 10 residues: {sequence_string[:10]} ------------------------+"
            )
            process_single_fasta_string(
                sequence_string=sequence_string,
                seq_hash=seq_hash,
                final_seq_dir=final_seq_dir,
                tmp_seq_dir=tmp_seq_dir,
                cpu=cpu,
                mem=mem,
            )


def process_single_fasta_string(
    *, sequence_string: str, seq_hash: str, final_seq_dir: Path, tmp_seq_dir: Path, cpu: int, mem: int
) -> None:
    """
    Generate a multiple sequence alignment (MSA) for a given sequence string.

    Performs the following steps:
        1) Generate a hash for the sequence.
        2) Perform iterative searches against UniRef30, trying to get more sequences with e-values within the specified cutoff.
        3) If the initial search against UniRef30 didn't yield enough sequences, perform iterative searches against BFD.

    Args:
        sequence_string (str): A single sequence string in fasta-compatible format (but not including the header).
        seq_hash (str): Hash of the sequence string.
        final_seq_dir (str): Path to the output directory. We will write the msa and other files to this directory upon completion.
        tmp_seq_dir (str): Path to the temporary directory. We will write the intermediate msa files to this directory, and clean up after completion.
        cpu (int): Number of cpus to use.
        mem (int): Maximum memory to use, in GB.
    """
    # ...create temporary directory if it doesn't exist (may exist already if a different worker is processing the same sequence, or previously failed)
    Path(tmp_seq_dir).mkdir(parents=True, exist_ok=True)

    # ...create a single-sequence fasta file based on the input sequence string, stored in the sequence directory
    fasta_file = os.path.join(tmp_seq_dir, f"{seq_hash}.fasta")
    with open(fasta_file, "w") as f:
        f.write(f">{seq_hash}\n{sequence_string}\n")

    # ...create temporary directory for hhblits output within the temporary sequence directory
    hhblits_tmp_dir = Path(tmp_seq_dir) / "hhblits_temp"
    Path(hhblits_tmp_dir).mkdir(parents=True, exist_ok=True)

    # ...and a file where we will save our final msa once we have enough sequences
    out_seq_msa_file = final_seq_dir / f"{seq_hash}.msa0.a3m"

    # Perform iterative searches against UniRef30:
    if not Path(out_seq_msa_file).exists():
        # ...set the starting file to the single-sequence fasta file
        prev_a3m = fasta_file

        # ...iterate over different e-value cutoffs to add sequences to the msa
        for e in [1e-10, 1e-3]:
            file_path_for_e_value = hhblits_tmp_dir / f"uniref_30.{e}.a3m"
            # ...run hhblits against uniref30, trying to get more sequences with e-values within the specified cutoff (if we haven't already processed this cutoff)
            if not Path(file_path_for_e_value).exists():
                run_hhblits(
                    input_file=prev_a3m,  # prev_a3m is either the single-sequence fasta file, or the 50% coverage, 90% identity output from the previous iteration
                    output_file=file_path_for_e_value,
                    db_path=uniref30_db_path,
                    cpu=cpu,
                    mem=mem,
                    e_value=e,
                    all_flag=False,  # NOTE: We could consider using the "-all" flag in this instance
                )
            else:
                logger.debug(
                    f"Skipping HHblits search against UniRef30 with e-value cutoff: {e}, since the file already exists"
                )

            # ...create a temporary file keeping track of sequences with 75% coverage and 90% identity
            uniref_30_id_90_cov_75 = f"{hhblits_tmp_dir}/uniref_30.{e}.id90cov75.a3m"
            if not Path(uniref_30_id_90_cov_75).exists():
                run_hhfilter(file_path_for_e_value, uniref_30_id_90_cov_75, 100000, 90, 75)
            # ...and create another temporary file keeping track of sequences with 50% coverage and 90% identity
            uniref_30_id_90_cov_50 = f"{hhblits_tmp_dir}/uniref_30.{e}.id90cov50.a3m"
            if not Path(uniref_30_id_90_cov_50).exists():
                run_hhfilter(file_path_for_e_value, uniref_30_id_90_cov_50, 100000, 90, 50)

            # ...count the number of sequences in the msa with 75% coverage
            logger.debug("Counting number of sequences with 75% and 50% coverage from UniRef30...")
            num_seq_with_75_percent_cov = int(
                subprocess.check_output(f"grep -c '^>' {uniref_30_id_90_cov_75}", shell=True)
            )
            num_seq_with_50_percent_cov = int(
                subprocess.check_output(f"grep -c '^>' {uniref_30_id_90_cov_50}", shell=True)
            )
            logger.debug(
                f"(UniRef) number of sequences with 75% coverage: {num_seq_with_75_percent_cov}, using e-value cutoff: {e}"
            )
            logger.debug(
                f"(UniRef) number of sequences with 50% coverage: {num_seq_with_50_percent_cov}, using e-value cutoff: {e}"
            )

            # ...set the previous a3m file to be the 90% identity, 50% coverage file, for the next iteration
            if Path(uniref_30_id_90_cov_50).exists():
                prev_a3m = f"{hhblits_tmp_dir}/uniref_30.{e}.id90cov50.a3m"

            # We want at least 2000 sequences with 75% coverage, or 4000 sequences with 50% coverage
            # When that happens, we copy whichever msa file met the criteria from the temporary to the output directory and break the loop
            if num_seq_with_75_percent_cov > 2000:  # NOTE: how does this change if we use the "-all" flag for uniref30?
                # ...we have enough sequences with 75% coverage, so we save the msa to our temporary directory and break the loop
                if not Path(out_seq_msa_file).exists():
                    logger.info(f"(UniRef) copying msa file with 75% coverage to output directory: {out_seq_msa_file}")
                    Path(final_seq_dir).mkdir(parents=True, exist_ok=True)
                    shutil.copy(uniref_30_id_90_cov_75, out_seq_msa_file)
                break
            elif num_seq_with_50_percent_cov > 4000:
                # ...we have enough sequences with 50% coverage, so we save the msa to our temporary directory and break the loop
                if not Path(out_seq_msa_file).exists():
                    logger.info(f"(UniRef) copying msa file with 50% coverage to output directory: {out_seq_msa_file}")
                    Path(final_seq_dir).mkdir(parents=True, exist_ok=True)
                    shutil.copy(uniref_30_id_90_cov_50, out_seq_msa_file)
                break

        # If the initial search against UniRef30 didn't yield enough sequences (since the msa file doesn't exist in the output location), we try bfd:
        if not Path(out_seq_msa_file).exists():
            e = 1e-3  # only one e-value cutoff for bfd
            file_path_for_e_value = hhblits_tmp_dir / f"bfd.{e}.a3m"

            # ...check if the intermediate msa file already exists
            if not Path(file_path_for_e_value).exists():
                # ...run hhblits against bfd, trying to get more sequences
                logger.debug(f"Running HHblits against BFD with e-value cutoff: {e}")
                run_hhblits(
                    input_file=prev_a3m,  # NOTE: we use the previous a3m file as input (the 50% coverage and 75% identity output from searching uniref30)
                    output_file=f"{hhblits_tmp_dir}/bfd.{e}.a3m",
                    db_path=bfd_db_path,
                    cpu=cpu,
                    mem=mem,
                    e_value=e,
                    all_flag=False,  # NOTE: we want to perform some de-duplication, since we don't have taxonomies
                )

            # ...filter the bfd msa to keep only sequences with 90% identity and 75% coverage, and save the output to a new file
            bfd_id_90_cov_75 = f"{hhblits_tmp_dir}/bfd.{e}.id90cov75.a3m"
            run_hhfilter(file_path_for_e_value, bfd_id_90_cov_75, 100000, 90, 75)

            # ...filter the bfd msa to keep only sequences with 90% identity and 50% coverage, and save the output to a new file
            bfd_id_90_cov_50 = f"{hhblits_tmp_dir}/bfd.{e}.id90cov50.a3m"
            run_hhfilter(file_path_for_e_value, bfd_id_90_cov_50, 100000, 90, 50)

            # ...set the previous a3m file to be the 90% identity, 50% coverage file (but there are no more iterations)
            if Path(bfd_id_90_cov_50).exists():
                prev_a3m = bfd_id_90_cov_50

            # ...count the number of sequences with 75% and 50% coverage
            logger.debug("Counting number of sequences with 75% and 50% coverage from BFD...")
            num_seq_with_75_percent_cov = int(subprocess.check_output(f"grep -c '^>' {bfd_id_90_cov_75}", shell=True))
            num_seq_with_50_percent_cov = int(subprocess.check_output(f"grep -c '^>' {bfd_id_90_cov_50}", shell=True))

            logger.debug(
                f"(BFD) number of sequences with 75% coverage: {num_seq_with_75_percent_cov}, using e-value cutoff: {e}"
            )
            logger.debug(
                f"(BFD) number of sequences with 50% coverage: {num_seq_with_50_percent_cov}, using e-value cutoff: {e}"
            )

            # Again, we want at least 2000 sequences with 75% coverage, or 4000 sequences with 50% coverage (cumulative from uniref30 and bfd)
            if num_seq_with_75_percent_cov > 2000:
                if not Path(out_seq_msa_file).exists():
                    # Copy the msa file with 75% coverage to the output directory
                    logger.info(f"(BFD) copying msa file with 75% coverage to output directory: {out_seq_msa_file}")
                    Path(final_seq_dir).mkdir(parents=True, exist_ok=True)
                    shutil.copy(bfd_id_90_cov_75, out_seq_msa_file)
            elif num_seq_with_50_percent_cov > 4000 and not Path(out_seq_msa_file).exists():
                # Copy the msa file with 50% coverage to the output directory
                logger.info(f"(BFD) copying msa file with 50% coverage to output directory: {out_seq_msa_file}")
                Path(final_seq_dir).mkdir(parents=True, exist_ok=True)
                shutil.copy(bfd_id_90_cov_50, out_seq_msa_file)

        # If we never had enough sequences from uniref30 or bfd, we just copy the last processed a3m file
        if not Path(out_seq_msa_file).exists() and Path(prev_a3m).exists() and prev_a3m != fasta_file:
            logger.info(
                f"Insufficient sequences after BFD seach; copying last processed a3m file to output directory: {out_seq_msa_file}"
            )
            Path(final_seq_dir).mkdir(parents=True, exist_ok=True)
            shutil.copy(prev_a3m, out_seq_msa_file)

    logger.info(f"+-------------------- Finished processing sequence with hash: {seq_hash} --------------------+")


def run_msa_pipeline(
    *,
    out_dir: str,
    num_workers: int,
    csv_file: str,
    mem: int = 64,
    task_id: int = 0,
    num_tasks: int = 1,
) -> None:
    logger.info(f"Launching task {task_id + 1} of {num_tasks}.")

    # Load the CSV file into a list
    df = pd.read_csv(csv_file, keep_default_na=False, na_values=NA_VALUES)
    sequences = df["q_pn_unit_processed_entity_non_canonical_sequence"].tolist()

    # Create a dictionary that maps sequence hashes to sequences
    logger.debug("Hashing sequences...")
    sequence_hash_to_sequence = {hash_sequence(sequence): sequence for sequence in sequences}

    # Get the sequences that have been processed already (that are in the output directory)
    logger.info("Checking for processed sequences...")
    processed_out_dir = Path(out_dir) / "processed"
    if processed_out_dir.exists():
        processed_hashes = {
            file.stem.split(".")[0] for file in processed_out_dir.rglob("*") if file.is_file() and file.suffix == ".a3m"
        }
    else:
        processed_hashes = set()

    # Get the sequence hashes that need to be processed
    sequence_hashes_to_process = list(set(sequence_hash_to_sequence.keys()) - processed_hashes)
    logger.info(f"Found {len(sequence_hashes_to_process)} sequences to process.")

    # Get the sequences corresponding to the hashes that need to be processed
    sequences_to_process = [sequence_hash_to_sequence[hash] for hash in sequence_hashes_to_process]

    # Randomly shuffle the list of sequences according to the task ID
    seed = task_id + time.time()
    logger.debug(f"Task {task_id}: Random seed: {seed}")
    random.seed(seed)
    random.shuffle(sequences_to_process)

    process_multiple_fasta_strings(sequences_to_process, out_dir, cpu=num_workers, mem=mem)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate multiple sequence alignments (MSAs) for structure prediction models."
    )
    parser.add_argument("--out-dir", type=str, required=True, help="Output directory where the results will be saved.")
    parser.add_argument("--num-workers", type=int, required=True, help="Number of CPUs to use for processing.")
    parser.add_argument("--csv-file", type=str, required=True, help="Path to the CSV file containing sequences.")
    parser.add_argument("--mem", type=int, default=64, help="Maximum memory to use, in GB. Default is 64.")
    parser.add_argument("--task-id", type=int, default=0, help="Task ID for parallel processing. Default is 0.")
    parser.add_argument(
        "--num-tasks", type=int, default=1, help="Number of tasks for parallel processing. Default is 1."
    )

    args = parser.parse_args()
    run_msa_pipeline(
        out_dir=args.out_dir,
        num_workers=args.num_workers,
        csv_file=args.csv_file,
        mem=args.mem,
        task_id=args.task_id,
        num_tasks=args.num_tasks,
    )
