stages:
  - test_fast
  - test_slow
  - post_merge

unit-test-job:
  coverage: '/TOTAL.*\s+(\d+%)$/'
  stage: test_fast
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_TITLE !~ /^(Draft|WIP):/i
      when: always
    - when: never
  script:
    - echo "Running fast unit tests"
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_fast_tests.sh

integration-test-job:
  coverage: '/TOTAL.*\s+(\d+%)$/'
  stage: test_slow
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_TITLE !~ /^(Draft|WIP):/i
      when: on_success
    - when: never
  needs:
    - job: unit-test-job
  script:
    - echo "Running slow tests"
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_slow_tests.sh

post-merge-job:
  coverage: '/TOTAL.*\s+(\d+%)$/'
  stage: post_merge
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run on main branch after merge
      when: always
    - when: never
  script:
    - echo "Running post-merge tests"
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_post_merge_tests.sh