stages:
  - test_fast
  - test_slow
  - post_merge
  - build_apptainer

unit-test-job:
  coverage: '/TOTAL.*\s+(\d+%)$/'
  stage: test_fast
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_TITLE !~ /^(Draft|WIP):/i
      when: always
      allow_failure: false
    - when: manual
      allow_failure: true
  script:
    - echo "Running fast unit tests"
    - set -e  # Exit immediately if a command exits with a non-zero status (so that we fail if the run gets killed)
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_fast_tests.sh || exit 1

integration-test-job:
  coverage: '/TOTAL.*\s+(\d+%)$/'
  stage: test_slow
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_TITLE !~ /^(Draft|WIP):/i
      when: on_success
      allow_failure: false
    - when: manual
      allow_failure: true
    - when: never
      allow_failure: true
  script:
    - echo "Running slow tests"
    - set -e  # Exit immediately if a command exits with a non-zero status (so that we fail if the run gets killed)
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_slow_tests.sh || exit 1

post-merge-job:
  coverage: '/TOTAL.*\s+(\d+%)$/'
  stage: post_merge
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run on main branch after merge
      when: always
    - when: never
  script:
    - echo "Running post-merge tests"
    - set -e  # Exit immediately if a command exits with a non-zero status (so that we fail if the run gets killed)
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/run_post_merge_tests.sh || exit 1

build-apptainer-job:
  stage: build_apptainer
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"
      changes:
        - apptainer.spec
        - environment.yaml
      when: manual
    - when: never
  script:
    - echo "Building Apptainer image"
    - srun -p cpu --cpus-per-task=1 --mem=32G bash ./.ci/build_apptainer.sh
    - echo "Apptainer image is available at /projects/ml/RF2_allatom/spec_files/datahub_$(DATE).sif"