name: datahub-dev  # development environment for datahub
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - openbabel=3.1.1
  - pytorch=2.2.0
  - rdkit=2024.3.5
  - pip
  - pip:
    # Project related dependencies
    # ... generic tools
    - cython>=3.0.0,<4  # Cython compiler for C extensions
    - cytoolz>=0.12.3,<1  # Cython-optimized tools for itertools and functional programming
    - assertpy>=1.1.0,<2  # Assertions library
    - tqdm>=4.65.0,<5  # Fast, extensible progress bar for loops and more
    # ... configuration & CLI
    - fire>=0.6.0,<1  # Better argument parsing than argparse
    - hydra-core>=1.3.0,<1.4  # Config management framework
    # ... linear algebra, maths & ml
    - numpy>=1.25.0,<2  
    - scipy>=1.13.1,<2
    - einops==0.7.0
    # ... data tools
    - pandas>=1.4.2,<2  # Data manipulation and analysis
    - pyarrow==17.0.0  # Columnar data format for efficient data storage and processing
    - fastparquet==2024.5.0  # Fast Parquet file format implementation
    # ... bioinformatics
    - biopython>=1.83,<2  # Collection of Python modules for bioinformatics
    - py3Dmol>=2.2.1,<3  # Python wrapper for 3Dmol.js
    - pymol-remote>=0.0.5  # Remote access to PyMOL from Python (has no dependencies)

    # Local packages
    - git+https://${GITLAB_USER}:${GITLAB_TOKEN}@git.ipd.uw.edu/ai/biotite.git@v1.0.1
    - git+https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/baker-laboratory/cifutils.git@v1.1.0

    # Formatting & linting
    - ruff==0.6.2  # python linter & formatter
    - pre-commit==3.7.1  # pre-commit hooks for formatting & linting

    # Debugger & interactive tools
    - debugpy>=1.8.5,<2  # debugger for python
    - ipykernel>=6.29.4,<7  # ipython kernel for jupyter

    # Pytest plugins
    - pytest>=8.2.0,<9  # testing framework
    - pytest-testmon>=2.1.1,<3  # run only tests related to changed code
    - pytest-xdist>=3.6.1,<4  # run tests in parallel
    - pytest-dotenv>=0.5.2,<1  # load environment variables from .env file
    - pytest-cov>=4.1.0,<5  # generate coverage report

    ## Not needed but possibly useful
    # jaxtyping
    # dotenv
    # wandb 
    # lightning

# NOTE: After navigating to the datahub directory, you can install the local package in editable mode with:
#   pip install -e .
